apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hansistage/uuzz/qxtcxo/8b1c3/v1.0/PUBLIC
      connectionConfig: 01ef0176-4197-1a28-9476-f6f6f7d7525d
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
