apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hwjsk/zkyf/bspmht/8b1c3/v1/PUBLIC
      connectionConfig:  01ef08b8-a494-1e20-b921-de6e6dee9223
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
