apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hwjsk/zkyf/bspmht/8b1c3/v1/PUBLIC
      connectionConfig:  01ef08ae-0ac8-1378-94cb-ccdf1af5c1e7
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
