apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/connections/mpcxsv/8b1c3/v1/PUBLIC
      connectionConfig: 01ef11d8-cce5-1e06-8eb8-719d1e1f094f
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

