apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: MI Hello world
      port: 8290
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: helloConfigs/src/main/resources/metadata/HelloWorld_swagger.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hansistage/uuzz/qxtcxo/8b1c3/v1.0/PUBLIC
      connectionConfig: 01ef017c-ddc4-1a86-8fb4-1838e936e1ea
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
