apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: MI Hello world
      port: 8290
      type: REST
      networkVisibility: Public
      context: /
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/isdtvy/8b1c3/v1/PUBLIC
      connectionConfig: 01eefd62-af9d-12d8-91b8-dc9d04e9eee1
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
