apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/isdtvy/8b1c3/v1/PUBLIC
      connectionConfig: 01ef031e-7c3c-13f0-ba3c-eefda67e6688
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

