apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Ballerina Greeter
      port: 8090
      type: REST
      networkVisibility: Public
      context: /hello
      schemaFilePath: hello_openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/tgazji/803f0/v2/PUBLIC
      connectionConfig: 01ef0199-170b-1116-993a-a37e63c2e00f
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

