apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Go Greeter
      port: 8090
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/connections/mpcxsv/8b1c3/v1/PUBLIC
      connectionConfig: 01ef11d9-8513-1888-9caf-0ba3571ff7e7
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

