apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Ballerina Greeter
      port: 8090
      type: REST
      networkVisibility: Public
      context: /hello
      schemaFilePath: hello_openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/isdtvy/8b1c3/v1/PUBLIC
      connectionConfig: 01ef038d-60bc-14d6-bd2c-102b2791821d
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

