apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Go Greeter
      port: 9090
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hwjsk/zkyf/bspmht/8b1c3/v1/PUBLIC
      connectionConfig: 01ef08b0-d276-128e-b7fd-2d39dedc5099
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
