apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Books REST Endpoint
      port: 5000
      type: REST
      networkVisibility: Public
      context: /reading-list
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/isdtvy/8b1c3/v1/PUBLIC
      connectionConfig: 01ef01e7-d1c2-1006-9e77-c4e6a720ba60
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
