apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Books REST Endpoint
      port: 5000
      type: REST
      networkVisibility: Public
      context: /reading-list
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///hwjsk/zkyf/bxolkw/20ce3/v1.1/PUBLIC
      connectionConfig: 01ef019d-4e7b-1bc8-9d1a-4e076c9f9d91
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
