apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hwjsk/zkyf/bspmht/8b1c3/v1/PUBLIC
      connectionConfig: 01ef0901-d716-1fd6-9807-5fd16689c01f
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

